# Generated by Django 5.1.2 on 2024-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0002_alter_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
