# Generated by Django 5.1.2 on 2024-10-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0003_produto_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tipos-de-produtos/'),
        ),
    ]
