# Generated by Django 5.1.2 on 2024-10-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0004_tipoproduto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproduto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tipos/'),
        ),
    ]
